resources:
  - ../../base

namePrefix: tito-client-1- # le probleme de no decrypt vient d'ici !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

commonLabels:
  tenant: tito-client-1
  app: tito-client-1

patchesStrategicMerge:
  - patch-ingress.yaml
  - patch-deployment.yaml

configMapGenerator:
  - name: config
    literals:
      - APP_URL=https://client1.tito.io
    options:
      disableNameSuffixHash: true
