resources:
  - ../../base

namePrefix: tito-client-1- # le probleme de no decrypt vient d'ici !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!

commonLabels:
  tenant: tito-client-1
  app: tito-client-1

patches:
  - path: patch-ingress.yaml
  - path: patch-deployment.yaml

configMapGenerator:
  - name: config
    literals:
      # - APP_NAME=Tito Client 1
      # - APP_ENV=production
      - APP_URL=https://client1.tito.io
    options:
      disableNameSuffixHash: true


# secretGenerator:
#   - name: secret
#     literals:
#       - APP_KEY=base64:T6UC4A92GV0d4GZUFjyim+YAaAuwFSLpR9pgGoMCztc=
#       - DB_PASSWORD=secret
#     options:
#       disableNameSuffixHash: true