resources:
  - ../../base

namePrefix: vic-

commonLabels:
  tenant: vic
  app: vic

patches:
  - path: patch-ingress.yaml
  - path: patch-deployment.yaml
    target:
      kind: Deployment

configMapGenerator:
  - name: config
    literals:
      # - APP_NAME=Tito Client 1
      # - APP_ENV=production
      - APP_URL=https://vic.tito.io
    options:
      disableNameSuffixHash: true
