resources:
  - ../../base

namePrefix: vic-

commonLabels:
  tenant: vic
  app: vic

patchesStrategicMerge:
  - patch-ingress.yaml
  - patch-deployment.yaml

configMapGenerator:
  - name: config
    literals:
      # - APP_NAME=Tito Client 1
      # - APP_ENV=production
      - APP_URL=https://vic.tito.io
    options:
      disableNameSuffixHash: true
