apiVersion: v1
kind: ConfigMap
metadata:
  name: config
data:
  APP_ENV: local
  APP_DEBUG: "true"
  APP_NAME: Kagoo
  APP_KEY: base64:T6UC4A92GV0d4GZUFjyim+YAaAuwFSLpR9pgGoMCztc=
  DB_CONNECTION: mysql
  DB_PORT: "3306"
  MAIL_DRIVER: smtp
  MAIL_HOST: smtp.sendgrid.net
  MAIL_PORT: "587"
  MAIL_FROM_NAME: "Kagoo"
  MAIL_FROM_ADDRESS: noreply@notifications.kagoo.io
  MAIL_USERNAME: apikey
  MAIL_ENCRYPTION: tls
  MAIL_REPLY_TO_NAME: "Kagoo Support"
  MAIL_REPLY_TO_ADDRESS: support@kagoo.io
