namespace: staging

resources:
  - deployment.yaml
  - service.yaml
  - ingress.yaml
  # - configs.yaml
  # - secrets-sealed.yaml
  # - migrate-seed-job.yaml

patchesStrategicMerge:
  - patch-ingress.yaml
  - patch-deployment.yaml
