apiVersion: v1
kind: Secret
metadata:
  name: secret
type: Opaque
stringData: #don't need to encode data
  APP_KEY: base64:t5jLs/vnsDgy7PGXus30tPCR0lKyb5lkMHPStvhmVVE=
  DB_HOST: 127.0.0.1
  DB_DATABASE: test
  DB_USERNAME: test
  DB_PASSWORD: test
  MAIL_PASSWORD: test
  
