apiVersion: v1
kind: Secret
metadata:
  name: secrets
  namespace: staging
data:
  #APP_KEY: YmFzZTY0OnQ1akxzL3Zuc0RneTdQR1h1czMwdFBDUjBsS3liNWxrTUhQU3R2aG1WVkU9
  DB_HOST: MTI3LjAuMC4x
  DB_DATABASE: dGVzdA==
  DB_USERNAME: dGVzdA==
  DB_PASSWORD: dGVzdA==
  MAIL_PASSWORD: dGVzdA==
